### ISSUE TITLE
Does not work with filtered indexes

### ISSUE THREAD

**Issue by MarkBird** [OpenDBDiff/OpenDBDiff#104]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of OpenDBDiff**

0.10.0.0

**What is the current behavior?**

OpenDBDiff does not detect an index has been changed to a filtered index

**What is the expected behavior or new feature?**

Should detect the index has changed

**Did this work in previous versions of our tool?  If so, in which versions?**

Did not work in 0.9 either

## Reproducibility
Please attach schema generation scripts for the relevant database objects. If your bug report is about changing existing entities (i.e. not creating or dropping an object), please attach the scheme generation scripts of the object before and after the change. This will enable the developers to reproduce your problem easily. Highlight particular areas of interest.

#### Before schema change:
```sql
CREATE UNIQUE NONCLUSTERED INDEX [IXU_NewsletterArticles_NewsletterId__ArticleId] ON [dbo].[NewsletterArticles]
(
	[NewsletterId] ASC,
	[ArticleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```

#### After schema change:
```sql
CREATE UNIQUE NONCLUSTERED INDEX [IXU_NewsletterArticles_NewsletterId__ArticleId] ON [dbo].[NewsletterArticles]
(
	[NewsletterId] ASC,
	[ArticleId] ASC
)
WHERE ([ArticleId] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```

**Comment by zyo2012** [comment]
I'm having the same issue.

**Comment by igitur** [comment]
Pull requests welcome.

**Comment by igitur** [comment]
Please add the schema scripts for the `NewsletterArticles` table so that I can run the index scripts.

**Comment by igitur** [comment]
Will reopen when schema scripts has been supplied, as requested.

**Comment by davebray131** [comment]
I am having this same issue.  Please reopen now that schema scripts are present in the issue.

**Comment by igitur** [comment]
@davebray131 Read my previous comments, please.

**Comment by davebray131** [comment]
You have no comments on this issue other than "Will reopen when schema scripts has been supplied, as requested" and then you closed the issue.

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/88838799-5bb6be00-d1da-11ea-8a37-085ca8dac83a.png)

**Comment by davebray131** [comment]
Do you need something more than the scripts that are provided in the issue?

![image](https://user-images.githubusercontent.com/5162040/88839138-3a38e080-d1a0-11ea-86b5-72cc19d15398.png)

**Comment by davebray131** [comment]
I went ahead and downloaded the source code and fixed it myself.  It looks like the problem is in the GenerateIndex.cs file.  The source is only working if the SQL version is 2008.

![image](https://user-images.githubusercontent.com/5162040/88841476-a9640400-d1a3-11ea-8966-ce2c16548b2e.png)

**Comment by igitur** [comment]
Great. If you want to contribute the fix back to the project, please open pull request.
