### ISSUE TITLE
Missing support with command line

### ISSUE THREAD

**Issue by Eldadc** [OpenDBDiff/OpenDBDiff#105]
Hi

Missing support to make compare via CLI.

Thanks

**Comment by jspraul** [comment]
Check out OCDB.exe in the [Release .ZIP file](https://github.com/OpenDBDiff/OpenDBDiff/releases/tag/0.10.0).

I don't think there's a writeup here on how it works, but I did find [this](https://www.databasejournal.com/features/mssql/article.php/3842326/Open-DBDiff-for-SQL-Server-2008.htm):

> The syntax for calling the OCDB.exe is:
> OCDB CN1="Connection String 1" CN2="Connection String 2" F=FileDestination.sql

**Comment by Eldadc** [comment]
Thanks !

**Comment by giansalex** [comment]
Good!, @Eldadc close issue.
