### ISSUE TITLE
Checked columns are not being properly compared.

### ISSUE THREAD

**Issue by cboyce428** [OpenDBDiff/OpenDBDiff#11]
To re-produce have two databases each which have different table columns e.g.

use [db1]
create table [Example] (Test int, Test2 varchar(20))
use [db2]
create table [Example] (Test int)

Within DBDiff expand Tables => [dbo].[Example] => Columns => Click on "Test2", you will note the sync script is completely blank.

This appears to be due to this line:

this.Where(item => (schemas.Count == 0 || schemas.FirstOrDefault(sch => sch.Id == item.Id) != default(ISchemaBase))).ToList().ForEach(item => { item.ResetWasInsertInDiffList(); listDiff.AddRange(item.ToSqlDiff().WarnMissingScript(item)); });

The "tag" of the checkbox list does not not match "schemas" id therefore its not being included.

**Comment by ironicnet** [comment]
I was able to reproduce this bug using this script for DB setup:
```
CREATE DATABASE [db1]
GO
CREATE DATABASE [db2]
GO
use [db1]
GO
create table [Example] (Test int, Test2 varchar(20), Test3 bigint)
use [db2]
GO
create table [Example] (Test int, Test3 bit)
GO
```
I'll try to take a look at the code causing it
