### ISSUE TITLE
Row number hidden with large stored/function 

### ISSUE THREAD

**Issue by nwandy** [OpenDBDiff/OpenDBDiff#111]
This is a little but signifiant bug.
When you have more then 100 rows in a table/stored/function, the row number is not shown completely (last version 0.10.0.0)

It's enough enlarge the row number column in PrincipalForm.cs at line 580:
scintilla.Margins[0].Width = 30;

Bye

**Comment by igitur** [comment]
Thanks. Seems like you're well on your way to a PR.
