### ISSUE TITLE
Item count in object tree would be better if it showed the number of visible items rather than the total count of objects

### ISSUE THREAD

**Issue by Mike55555** [OpenDBDiff/OpenDBDiff#152]
- [x] Feature

**Version of OpenDBDiff**
0.13.0.0

**What is the current behavior?**
Currently the item count in the object tree shows the total count of all objects. For example, my database has 423 stored procs, so it says "Stored Procedures (423)".

**What is the expected behavior or new feature?**
It would be more helpful if the count reflected the number of items that are displayed. So for example if I untick "Show unchanged items", and now my list gives me just the 12 procs that are different or new, then I'd expect the node to say "Stored Procedures (12)". This would make it easier to see how many differences I have to resolve.   Ideally the root node (the database name) would show the total number of differences for all object types.

**Did this work in previous versions of our tool?  If so, in which versions?**
No

**Comment by jspraul** [comment]
@Mike55555 Thanks for this request. You can download a build including this tweak [from AppVeyor](https://ci.appveyor.com/api/buildjobs/glmtrogl8e8spmnu/artifacts/OpenDBDiff%2Fbin%2FOpenDBDiff.CI.zip).

**Comment by Mike55555** [comment]
Nice one! That works beautifully. Many thanks!
