### ISSUE TITLE
Where is the location of the OpenDBDiff project that is saved? 

### ISSUE THREAD

**Issue by CoupDavil** [OpenDBDiff/OpenDBDiff#171]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**Version of OpenDBDiff**

 0.13

**What is the current behavior?**

I'm trying to do a database comparison for a customer I'm currently working with. When saving the project I do not know where this is saved and it's very unclear. I've tried to look at documentation and I've found nothing useful so far. Would like to see after saving where it's being saved and open project should show saved location.

**What is the expected behavior or new feature?**

Show saved location and open saved location

**Did this work in previous versions of our tool?  If so, in which versions?**

This would be a feature

**Comment by igitur** [comment]
The settings file should be located at `C:\Users\<insert your username>\AppData\Local\OpenDBDiff\settings.liteDb` . It is a https://www.litedb.org/ database.
