### ISSUE TITLE
Invited as contributor

### ISSUE THREAD

**Issue by AndersBillLinden** [OpenDBDiff/OpenDBDiff#18]
I need to check if it was on purpose that I was invited as contributor.

/Anders

**Comment by jspraul** [comment]
I wanted to thank everyone who had been involved with the project in some way. Any participation is appreciated; so many have come & gone without a word!

https://news.ycombinator.com/item?id=15765575

It's been nearly 10 years; in the spirit of "the pull request hack" I've invited you as a collaborator. Please forgive the intrusion if this is just a case of mistaken identity with the same username.

https://felixge.de/2013/03/11/the-pull-request-hack.html

http://opendbdiff.codeplex.com/wikipage?title=Contributions%20Welcome&version=1
