### ISSUE TITLE
Inconsistent Labels

### ISSUE THREAD

**Issue by netsec4u** [OpenDBDiff/OpenDBDiff#2]
In various locations within the application, the naming between two databases is not consistent.  At the top, the two databases to compare are referred to as source and destination.  Then, on the schema tab, it is referred to as new and old object.  Also, on the Schema tab, it is also referred to as new and existing object.  In the compare data window, the two databases are referred to as source and destination.

To eliminate confusion, all references to the two databases should be consistent throughout the application.

**Comment by ironicnet** [comment]
Noted, will change the "old" for existing in the objects label.

The database labels are OK, as they are source and destination. _New_ and _Existing_ should refer to objects only.

**Comment by ironicnet** [comment]
Well. I left the "Old" text, and replaced the "Existing" ones.
As "New" and "Old" are opposites. While "New" and "Existing" not so much.
