### ISSUE TITLE
Error Loading Source Database (while initializing)

### ISSUE THREAD

**Issue by G4a8bo** [OpenDBDiff/OpenDBDiff#23]
Open DBDiff Beta 0.9.0.0
Error Loading Source Database (while initializing)
SqlException: Si è verificato un errore di rete o specifico dell'istanza mentre si cercava di stabilire una connessione con il server SQL. Il server non è stato trovato o non è accessibile. Verificare che il nome dell'istanza sia corretto e che il server SQL sia configurato in modo da consentire connessioni remote. (provider: Provider Named Pipes, error: 40 - Impossibile aprire una connessione a SQL Server)
   in System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection)
   in System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj)
   in System.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, SqlConnection owningObject, Boolean withFailover)
   in System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnection owningObject, Boolean withFailover)
   in System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(String host, String newPassword, Boolean redirectedUserInstance, SqlConnection owningObject, SqlConnectionString connectionOptions, Int64 timerStart)
   in System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(SqlConnection owningObject, SqlConnectionString connectionOptions, String newPassword, Boolean redirectedUserInstance)
   in System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, String newPassword, SqlConnection owningObject, Boolean redirectedUserInstance)
   in System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection)
   in System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnection owningConnection, DbConnectionPool pool, DbConnectionOptions options)
   in System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject)
   in System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject)
   in System.Data.ProviderBase.DbConnectionPool.GetConnection(DbConnection owningObject)
   in System.Data.ProviderBase.DbConnectionFactory.GetConnection(DbConnection owningConnection)
   in System.Data.ProviderBase.DbConnectionClosed.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   in System.Data.SqlClient.SqlConnection.Open()
   in DBDiff.Schema.SQLServer.Generates.Generates.GenerateDatabase.Get(Database database) in c:\projects\opendbiff\DBDiff.Schema.SQLServer2005\Generates\GenerateDatabase.cs:riga 37
   in DBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in c:\projects\opendbiff\DBDiff.Schema.SQLServer2005\Generates\Generate.cs:riga 87
   in DBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, EventArgs e) in c:\projects\opendbiff\DBDiff\Front\ProgressForm.cs:riga 64

F4BF557B504CA2F9C0EAD07B9D6615FF

**Comment by ironicnet** [comment]
Is the server accessible? That's the standard connection error when not being able to reach the sql server instance.

**Comment by G4a8bo** [comment]
I access to the server via vpn, some time the vpn is slow. 
After this error i have to exit and restart the app. 

Sorry for my english. 

Inviato da mobile

**Comment by ironicnet** [comment]
OK. So after this error occurs, the app crashes and you have to restart it?

I'll try to reproduce it (should be easy) and push a fix for the next version.

And your English is fine, mine isn't perfect either.

Grazie e saluti!

**Comment by G4a8bo** [comment]
After this error the app wan't connect to the server. Now i am in holidays, i can be more specific in new year when i came back to work. 

Gabriel Barbieri

**Comment by G4a8bo** [comment]
Back to work, i have simulate the error:
- turn off vpn
- click "Compare"
- click "Ok" on error form
- turn on vpn
- click "Compare"
It work normaly, i think it was a problme with the vpn stability. Sorry.

**Comment by ironicnet** [comment]
Great then!. Closing the issue then.

Have a great new year!
