### ISSUE TITLE
DAta Comparison Window

### ISSUE THREAD

**Issue by rdcloud85** [OpenDBDiff/OpenDBDiff#3]
I cloned your project several weeks ago, as I like what it does. However, when I go into the 'data comparison' window... the panels don't resize with the window. I have added a split-panel to my local version and would like to upload it. However, I don't as yet have the authority to push my changes... I'm still new to GIT... so, please let me know what I need to do, in order to upload my changes for your review.

**Comment by igitur** [comment]
I'm working on a slight redesign of the UI and I will look into this issue too. 

To submit changes, read up on [pull requests](https://help.github.com/articles/about-pull-requests/).

**Comment by ironicnet** [comment]
@igitur can you create a branch with your changes? 

I did some changes to the GUI and how the project references. I hope I didn't break any of your changes.
