### ISSUE TITLE
Copyright issues

### ISSUE THREAD

**Issue by igitur** [OpenDBDiff/OpenDBDiff#31]
I noticed in the `AssemblyInfo.cs` files that the copyright is attributed to EGSOFT or EDS. Is this still true and can we remove it otherwise? I'm not clued up about these issues.

**Comment by jspraul** [comment]
I contacted the original author, he stated this is the name of his company and can be removed.

If he chooses not to respond here directly I will quote the email.

**Comment by igitur** [comment]
Thanks. I'll go ahead and remove the info.
