### ISSUE TITLE
Update selected button greyed out

### ISSUE THREAD

**Issue by JonnyTech** [OpenDBDiff/OpenDBDiff#4]
I performed a compare then selected a couple of items but the "Update selected" button is greyed out. "Compare data" is also greyed but "Update all" is ok. What should I do to make it available?

**Comment by ironicnet** [comment]
I know that this is an old question. But have you selected an object with changes in the tree view? It should enable those buttons

**Comment by ironicnet** [comment]
Closing this issue as this is was initially like a year old
