### ISSUE TITLE
OpenDBDiff or Open DBDiff

### ISSUE THREAD

**Issue by igitur** [OpenDBDiff/OpenDBDiff#48]
`OpenDBDiff` or `Open DBDiff`

I'm pedantic, so I'd like to know which version is the actual correct one. 

I prefer `OpenDBDiff` (no spaces and capitalisation like that), because it eases folder names and namespaces. Space characters just cause issues. 

cc @jspraul , @ironicnet

**Comment by ironicnet** [comment]
To me the project  is _Open DB Diff_. But in code or folders I would use ```OpenDBDiff``` as you suggested

**Comment by jspraul** [comment]
OpenDBDiff

**Comment by jspraul** [comment]
Feels settled, but anyone should always feel free to re-open / comment. Just cleaning up the issues a bit here.
