### ISSUE TITLE
OCDB executable inside last CI build

### ISSUE THREAD

**Issue by ElCondor1969** [OpenDBDiff/OpenDBDiff#50]
It would be very convenient if the OCDB. EXE executable were also present inside the last CI build.

**Comment by igitur** [comment]
Fixed in #51

**Comment by igitur** [comment]
For what do you use OCDB? And what does OCDB stand for anyway?

**Comment by ElCondor1969** [comment]
The OCDB executable allows you to create the SQL script by console, performing the operation automatically without needing to use manually the user interface.

The use of OCDB is described in this article that I found online:
https://www.databasejournal.com/features/mssql/article.php/3842326/Open-DBDiff-for-SQL-Server-2008.htm

**Comment by igitur** [comment]
> ...provided by Microsoft...

Say what?!

**Comment by ElCondor1969** [comment]
> C:\
CD "C:\Program Files (x86)\Open DBDiff"
OCDB CN1="Data Source=PowerPC\SQL2008;Initial Catalog=TestDB1;Integrated Security=SSPI;" 
  nullCN2="Data Source=PowerPC\SQL2008;Initial Catalog=TestDB2;Integrated Security=SSPI;" F="C:\test.sql"

I saw how to use the OCDB executable from the article above.
I can't say any more.

**Comment by igitur** [comment]
"Say what" is just an expression. https://www.urbandictionary.com/define.php?term=say%20what&utm_source=search-action

**Comment by ElCondor1969** [comment]
Ah, ok! ;)
