### ISSUE TITLE
Error compare

### ISSUE THREAD

**Issue by jhofran** [OpenDBDiff/OpenDBDiff#60]
User data type

DIFF-ERROR 0x00000040.008: Missing CreateStatus script for UserDataType 'TVP_GE_M_PROVEEDOR'

CREATE TYPE [dbo].[TVP_GE_M_PROVEEDOR] FROM [] NOT NULL

DROP TYPE [dbo].[TVP_GE_M_PROVEEDOR]

do not compare

**Comment by jspraul** [comment]
This looks very similar to #54.

Thanks for taking the time to share another example of this problem. Please review the discussion there as this issue is resolved.

I am going to go ahead and close this as a duplicate; if it turns out that it is not please feel free to re-open.
