### ISSUE TITLE
Crash when comparing stored procedures

### ISSUE THREAD

**Issue by NeilMJohnson** [OpenDBDiff/OpenDBDiff#68]
An unexpected error has occured during processing.

    1. To report an error please, search first in the github issues to see if it's already solved.
    2a. If there is no issue, *Please* click 'Create New Issue' and paste the error details
        into the Description field. To copy the error press _Copy Error_
        (At least email the details to opendbdiff@gmail.com...)

    2b. If the issue exists, but your situation is different please leave a comment with the details.

    • If possible, please attach a SQL script creating two dbs with
        the minimum necessary to reproduce the problem.
    
Error Information
```
Error Loading Destination Database (while Reading stored procedures: [SelectBorrowerByMortgageID])
NullReferenceException: Object reference not set to an instance of an object.
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.GenerateStoredProcedures.FillParameters(Database database, String connectionString) in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Generates\GenerateStoredProcedures.cs:line 74
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.GenerateStoredProcedures.Fill(Database database, String connectionString) in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Generates\GenerateStoredProcedures.cs:line 125
   at OpenDBDiff.Schema.SQLServer.Generates.Generates.Generate.Process() in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer.Generates\Generates\Generate.cs:line 141
   at OpenDBDiff.Schema.SQLServer.Generates.Front.SQLServerGenerator.Process() in C:\projects\opendbdiff\OpenDBDiff.Schema.SQLServer2005\Front\SQLServerGenerator.cs:line 36
   at OpenDBDiff.Front.ProgressForm.ProgressForm_Activated(Object sender, EventArgs e) in C:\projects\opendbdiff\OpenDBDiff\Front\ProgressForm.cs:line 63
```
850A5FEDA146AAA8473BB301E38ABE7B

The stored procedure is:
```sql
/****** Object:  StoredProcedure [dbo].[SelectBorrowerByMortgageID]    Script Date: 03/05/2018 13:13:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SelectBorrowerByMortgageID]') AND type in (N'P', N'PC'))
BEGIN
EXEC dbo.sp_executesql @statement = N'
CREATE   PROCEDURE [dbo].[SelectBorrowerByMortgageID]
(
	@MortgageID int
)
AS
	SET NOCOUNT ON;
	SELECT * 
		from	vwBorrowers
		WHERE (ID IN (SELECT BorrowerID 
				FROM MortgageApplicants 
				WHERE (MortgageID = @MortgageID)));
' 
END
GO

GRANT EXECUTE ON [dbo].[SelectBorrowerByMortgageID] TO [Administration] AS [dbo]
GO

GRANT EXECUTE ON [dbo].[SelectBorrowerByMortgageID] TO [InternalBroker] AS [dbo]
GO

GRANT EXECUTE ON [dbo].[SelectBorrowerByMortgageID] TO [Management] AS [dbo]
GO
```

**Comment by NeilMJohnson** [comment]
BTW, this happened during a complete compare of the two databases.

**Comment by igitur** [comment]
Which version of OpenDBDiff did you use? Could you try with the latest development CI build to be found at https://ci.appveyor.com/project/OpenDBDiff/OpenDBDiff/branch/develop/artifacts ?

**Comment by MarkGaze** [comment]
I just had the exact same issue, it happened because `database.CLRProcedures[reader["ObjectName"].ToString()]` 
in GenerateStoredProcedures.cs returned null so there wasn't a `Parameters` property to add to.

I solved it by changing the code to:


```csharp
var clrProcedure = database.CLRProcedures[reader["ObjectName"].ToString()];
if (clrProcedure != null)
  clrProcedure.Parameters.Add(param);
```

But that just works around the issue, I think... facing another problem at the moment with comparing so when I've got that working then I'll see if the missing parameter is shown in the diff.

**Comment by MarkGaze** [comment]
I used that version originally but then cloned the repo onto my machine and ran the latest in develop

**Comment by igitur** [comment]
@MarkGaze Can you possibly attach the 2 creation schemas of the 2 databases, specifically the parts which generate the CLR procedures?

**Comment by MarkGaze** [comment]
@igitur I work in a heavily-regulated business sector so I can't really share the details of those databases but when I get chance, I'll try and recreate the issue in a test DB and get back to you :)

**Comment by igitur** [comment]
Can you tell me what your value for `reader["ObjectName"].ToString()` is and whether a CLR procedure with that name exists? It should.

**Comment by MarkGaze** [comment]
The `reader["ObjectName"].ToString()` value is "[dbo].[CalculateTimespan]" and it does exist on the database.

Apologies for being a bit evasive with this!

**Comment by igitur** [comment]
So if you enumerate the entries in `database.CLRProcedures.Select(p => p.Name)` do you see anything that resembles `CalculateTimespan` ?

**Comment by MarkGaze** [comment]
No, `CalculateTimespace` doesn't exist in `CLRProcedures`. 

Having had a look in the database, the GetProcedures.sql script doesn't return them so just trying to figure out why.

**Comment by MarkGaze** [comment]
Looks like it's the type of the CLR procedure, the script is returning all `PC = Assembly (CLR) stored-procedure` types but this specific proc is of type `FS = Assembly (CLR) scalar-function` ([Reference](https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-objects-transact-sql))

Just trying a modified script and a change to `GenerateStoredProcedures` to see if that solves the original problem

**Comment by igitur** [comment]
@NeilMJohnson Does the build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.9.0.75/artifacts solve your issue too?

**Comment by igitur** [comment]
#71 breaks normal stored procedures' comparison. Please give me a way to reproduce the issue and I will fix it.

**Comment by MarkGaze** [comment]
What error do you get? The comparison was already broken for me so need to fix it to check that the change in #71 is valid

**Comment by igitur** [comment]
*Please give me a way to reproduce the issue and I will fix it.*

**Comment by MarkGaze** [comment]
To recreate you need a CLR scalar function in your database.

But I've checked in a fix to #71 anyway

**Comment by MarkGaze** [comment]
Seems good to me @igitur. 

Thanks.

**Comment by MarkGaze** [comment]
I still have another issue though so will log it for you to look into
