### ISSUE TITLE
No Instructions about how to install...

### ISSUE THREAD

**Issue by toferj** [OpenDBDiff/OpenDBDiff#7]
I'm lost as to how to install the OpenDBDiff application so I can actually use it. Do I need to compile it from source? If so, where are the instructions for that. I need a tool like this, and I'm sad that I came so close to finding one only to not be able to use it. :(

**Comment by jspraul** [comment]
We are transitioning from CodePlex, this is a great point.

Right now I would recommend downloading [the latest build from the (semi-) CI server](https://ci.appveyor.com/project/OpenDBDiff/opendbiff/build/artifacts), unzipping, and running.

**Comment by toferj** [comment]
Thanks! :smiley:
