### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jhofran** [OpenDBDiff/OpenDBDiff#70]
![sin titulo](https://user-images.githubusercontent.com/8104986/37502052-fce47822-289e-11e8-83e3-8c461d471c37.png)

System.ArgumentException: La longitud de la cadena no puede ser cero.
Nombre del parámetro: oldValue
   en System.String.ReplaceInternal(String oldValue, String newValue)
   en System.String.Replace(String oldValue, String newValue)
   en OpenDBDiff.Front.ErrorForm.LoadException(Exception ex) en C:\projects\opendbdiff\OpenDBDiff\Front\ErrorForm.cs:línea 45
   en OpenDBDiff.Front.ErrorForm..ctor(Exception ex) en C:\projects\opendbdiff\OpenDBDiff\Front\ErrorForm.cs:línea 26
   en OpenDBDiff.Front.PrincipalForm.HandleException(String errorLocation, Exception ex) en C:\projects\opendbdiff\OpenDBDiff\Front\PrincipalForm.cs:línea 262
   en OpenDBDiff.Front.PrincipalForm.btnCompare_Click(Object sender, EventArgs e) en C:\projects\opendbdiff\OpenDBDiff\Front\PrincipalForm.cs:línea 252
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by jhofran** [comment]
very good, solved.

**Comment by igitur** [comment]
ok thanks.
