### ISSUE TITLE
Default field issue

### ISSUE THREAD

**Issue by ElCondor1969** [OpenDBDiff/OpenDBDiff#75]
The problem occurs when a table has a field with a defined default value:

```sql
CREATE TABLE [dbo].[Collezioni] 
 ( 
 	[IDCollezione] [int] IDENTITY (1,1) NOT NULL, 
 	[DataInserimento] [datetime] NOT NULL CONSTRAINT [DF_Collezioni_DataInserimento] DEFAULT (getdate())
 ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

When OpenDBDiff generates the script, a temporary copy of the table with the same structure is created:

```sql
CREATE TABLE [dbo].[TempCollezioni] 
 ( 
 	[IDCollezione] [int] IDENTITY (1,1) NOT NULL, 
 	[DataInserimento] [datetime] NOT NULL CONSTRAINT [DF_Collezioni_DataInserimento] DEFAULT (getdate())
 ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

but this script will fail because the default **DF_Collezioni_DataInserimento** already exists in the original table **Collezioni**.
You should first to drop the default **DF_Collezioni_DataInserimento** before creating the temporary table.

**Comment by igitur** [comment]
Would this script solve your issue?
```sql
ALTER TABLE [dbo].[Collezioni] DROP CONSTRAINT [DF_Collezioni_DataInserimento]

CREATE TABLE [dbo].[TempCollezioni]
(
	[IDCollezione] [int] IDENTITY (1,1) NOT NULL,
	[DataInserimento] [datetime] NOT NULL CONSTRAINT [DF_Collezioni_DataInserimento] DEFAULT (getdate())

) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

INSERT INTO [dbo].[TempCollezioni] ([DataInserimento]) SELECT [DataInserimento] FROM [dbo].[Collezioni]
DROP TABLE [dbo].[Collezioni]
GO
EXEC sp_rename N'[dbo].[TempCollezioni]',N'Collezioni', 'OBJECT'
GO
```

**Comment by igitur** [comment]
https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.9.0.89/artifacts

Please try the build at that location. I hope it correctly drops all constraints before creating the temporary table.

**Comment by ElCondor1969** [comment]
Hi Igitur.
I tried and for me works.
Thank you.
