### ISSUE TITLE
Error User Table Types

### ISSUE THREAD

**Issue by jhofran** [OpenDBDiff/OpenDBDiff#85]
incorrect
```sql
CREATE TYPE [dbo].[TVP_ATTLOG] FROM [] NOT NULL
```

correct
```sql
CREATE TYPE [dbo].[TVP_ATTLOG] AS TABLE(
	[TARJETA] [varchar](30) NOT NULL,
	[HORA] [datetime] NOT NULL,
	[FECHA] [date] NOT NULL,
	[RELOJ] [varchar](5) NOT NULL
)
GO
```

![error 01](https://user-images.githubusercontent.com/8104986/39152499-37670770-470e-11e8-917d-8272c9b54b13.png)

**Comment by igitur** [comment]
I can't replicate this issue. What version of OpenDBDiff are you using?

**Comment by jhofran** [comment]
OpenDBDiff  v0.10.0.106
Microsoft SQL Server 2016 (SP1-GDR)

**Comment by igitur** [comment]
Ok, I can reproduce this on MS SQL Server 2016. It wasn't a problem on lower versions.

**Comment by igitur** [comment]
Please test this with the build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.10.0.117/artifacts

**Comment by jhofran** [comment]
revised, but it does not eliminate because it has a dependency with store procedure.

1.- drop procedure dependency
2.- drop TYPE [TVP_ATTLOG]
3.- create TYPE [TVP_ATTLOG]
4.- create procedure dependency

**Comment by igitur** [comment]
That's a different problem. Please log a new issue and complete the full issue template.

**Comment by jhofran** [comment]
if you're right, 

closed.
