### ISSUE TITLE
Synonyms are not part of compare configuration options

### ISSUE THREAD

**Issue by vishalatwork** [OpenDBDiff/OpenDBDiff#86]
- [x] Bug

**Version of OpenDBDiff** : 0.10.0.0

First of , Great work on the project , I would like to report here a small issue 

If you see Compare Options window , there are diff. schema types are there , I don't know for what reasons Synonyms doesn't appear over here.

Attached screenshot : 

![image](https://user-images.githubusercontent.com/34301488/39417233-7801addc-4c70-11e8-8397-88d2b51009b1.png)

**Comment by igitur** [comment]
Please test this issue with the build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.10.0.112/artifacts
