### ISSUE TITLE
Clarification needed on how Exclude by name is working as it is not working for a pattern atleast

### ISSUE THREAD

**Issue by vishalatwork** [OpenDBDiff/OpenDBDiff#87]
- [x] Bug

**Version of OpenDBDiff** : 0.10.0.0

Here are different cases I tried with "Exclude by Name",

If you give an exact match of object then it will work , but not pattern wise.

for e.g.

If you select StoredProcedure and want to ignore sp_alterdiagram then you will require to pass full name.

If I want to ignore all stored procedures start with **sp_** , then specifying pattern **sp_*** is not working.

Please Clarify if this is supported or an alternatives to achieve same.

**Comment by igitur** [comment]
This wasn't supported before. I have now implemented pattern matching using wildcards. Please test this issue with the build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/build/0.10.0.113/artifacts

**Comment by vishalatwork** [comment]
Great work @igitur , I have tested this out and its working as expected :+1:
