### ISSUE TITLE
Feature User Table Types and Store Procedure

### ISSUE THREAD

**Issue by jhofran** [OpenDBDiff/OpenDBDiff#91]
actual process
1.- drop Type Table
2.- create Type Table
3.-Alter Store Procedure

generates error because it has dependence

process order

1.- drop procedure dependency
2.- drop TYPE [TVP_ATTLOG]
3.- create TYPE [TVP_ATTLOG]
4.- create procedure dependency

**Comment by igitur** [comment]
You totally ignored the issue template even after I asked you to populate it?!

**Comment by jhofran** [comment]
perdón lo volveré hacer, siguiendo la plantilla.

**Comment by jhofran** [comment]
Close, please.
