### ISSUE TITLE
All tables not being scanned/shown

### ISSUE THREAD

**Issue by anubissystemlord** [OpenDBDiff/OpenDBDiff#97]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of OpenDBDiff**
0.10.0.0

**What is the current behavior?**
When scanning for changes only 9 tables are being displayed in the tables section; a large number of tables (and table changes) are missing from both the display but also the change script.

**What is the expected behavior or new feature?**
All tables should display.

**Did this work in previous versions of our tool?  If so, in which versions?**
Not sure, this is the first version I've tried.

## Reproducibility
Each time I run the program I get the same result.  See screenshots showing more tables in SSMS vs. OpenDBDiff.

Snip from SSMS:
![image](https://user-images.githubusercontent.com/25586328/46676445-4438ca80-cc2c-11e8-9a7a-f1ed05bd77ac.png)

Snip from OpenDBDiff:
![image](https://user-images.githubusercontent.com/25586328/46676494-62062f80-cc2c-11e8-8d2a-6da20d212cf8.png)

**Comment by igitur** [comment]
Attach the full schema generation script that SSMS can produce.

**Comment by anubissystemlord** [comment]
Hi igitur,

I'm sorry, I'm not permitted to post that, but with a little more trial and error, I found out what is causing the issue.

It seems to be the long identity seed for a 'bigint' identity column for this table.  A way to reproduce it is via:


CREATE TABLE [dbo].[ATestTable](
	[CircuitID] [int] NOT NULL,
	[DrawID] [bigint] IDENTITY(2018100600000000000,1) NOT NULL,
 CONSTRAINT [PK_ATestTable] PRIMARY KEY CLUSTERED 
(
	[DrawID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


This looks like it might be an overflow issue of some kind?

Thanks
Anubis.

**Comment by igitur** [comment]
If I use that script to generate the `ATestTable` and do an OpenDBDiff comparison, I can see the table, but that particular `DrawID` column doesn't show.

**Comment by igitur** [comment]
Please try the CI build at https://ci.appveyor.com/project/OpenDBDiff/opendbdiff/builds/19401245/artifacts

**Comment by anubissystemlord** [comment]
Hi Francois,

 

Thank you, this works and now lists all the tables.

 

Thanks

Anubis.
